### ISSUE TITLE
Crash Followed by Java update

### ISSUE THREAD

**Issue by ltfuzzle** [d2rm/d2rm#11] opened 2015-02-09 15:32 UTC
After Syncing, it says an error has occured and it has been writen to the dota.log file or something, I need to go back and check and then it opens like 15 tabs telling me to download java. I'll see if I can find the log file.

EDIT1: I cant seem to find the dota.log file.

**Comment by pyarmak** [comment] 2015-02-09 19:22
On linux, you need Java 1.7 or higher to run the actual replay parser. The JRE is bundled with the windows version so Java is not needed. I don't know of a way to bundle a JRE for linux.

Information on the location of log files on different systems can be found [here](https://github.com/nwjs/nw.js/wiki/Crash-dump).

**Comment by ltfuzzle** [comment] 2015-02-09 19:27
I am also on Windows 8.1 64bit, not linux. Ill upload the crash shortly.

**Comment by pyarmak** [comment] 2015-02-09 19:38
In that case, the logs are stored in ```C:\Users\<USERNAME>\AppData\Local\D2RM```.
Please provide me with the exception and dota logs so I can diagnose the problem. If you have experienced crashed on multiple occasions, please erase these two files then re-create the crash and send me the newly created log files. This makes my life easier when trying to find the source of the error.

I'm also not entirely clear what you mean by:
> I need to go back and check and then it opens like 15 tabs telling me to download java

**Comment by ltfuzzle** [comment] 2015-02-09 19:53
There is no exceptions file. The dota file is as follows. This was after deleting it then opening it again.


09T19:50:39.052Z - info: [PARSER] match 1223182984
2015-02-09T19:50:39.053Z - info: [PARSER] found local replay for match 1223182984
2015-02-09T19:50:39.053Z - info: [PARSER] running parse on C:\Program Files (x86)\Steam\SteamApps\common\dota 2 beta\dota\replays\1223182984.dem
2015-02-09T19:50:39.453Z - info: [PARSER] Finished parsing 1223182984
2015-02-09T19:50:39.453Z - error: [PARSER] Error: Error: Command failed: 
2015-02-09T19:50:39.453Z - info: [PARSER] match 1223402659
2015-02-09T19:50:39.454Z - info: [PARSER] found local replay for match 1223402659
2015-02-09T19:50:39.454Z - info: [PARSER] running parse on C:\Program Files (x86)\Steam\SteamApps\common\dota 2 beta\dota\replays\1223402659.dem
2015-02-09T19:50:39.927Z - info: [PARSER] Finished parsing 1223402659
2015-02-09T19:50:39.927Z - error: [PARSER] Error: Error: Command failed: 
2015-02-09T19:50:39.929Z - info: [PARSER] match 1223342567
2015-02-09T19:50:39.929Z - info: [PARSER] found local replay for match 1223342567
2015-02-09T19:50:39.929Z - info: [PARSER] running parse on C:\Program Files (x86)\Steam\SteamApps\common\dota 2 beta\dota\replays\1223342567.dem
2015-02-09T19:50:40.501Z - info: [PARSER] Finished parsing 1223342567
2015-02-09T19:50:40.504Z - error: [PARSER] Error: Error: Command failed: 
2015-02-09T19:50:40.504Z - info: [PARSER] match 1222834290
2015-02-09T19:50:40.504Z - info: [PARSER] found local replay for match 1222834290
2015-02-09T19:50:40.504Z - info: [PARSER] running parse on C:\Program Files (x86)\Steam\SteamApps\common\dota 2 beta\dota\replays\1222834290.dem
2015-02-09T19:50:41.070Z - info: [PARSER] Finished parsing 1222834290
2015-02-09T19:50:41.070Z - error: [PARSER] Error: Error: Command failed: 
2015-02-09T19:50:41.071Z - info: [PARSER] match 1223139848
2015-02-09T19:50:41.071Z - info: [PARSER] found local replay for match 1223139848
2015-02-09T19:50:41.071Z - info: [PARSER] running parse on C:\Program Files (x86)\Steam\SteamApps\common\dota 2 beta\dota\replays\1223139848.dem
2015-02-09T19:50:41.690Z - info: [PARSER] Finished parsing 1223139848
2015-02-09T19:50:41.691Z - error: [PARSER] Error: Error: Command failed: 
2015-02-09T19:50:41.692Z - info: [PARSER] match 1208222291
2015-02-09T19:50:41.692Z - info: [PARSER] found local replay for match 1208222291
2015-02-09T19:50:41.692Z - info: [PARSER] running parse on C:\Program Files (x86)\Steam\SteamApps\common\dota 2 beta\dota\replays\1208222291.dem
2015-02-09T19:50:42.208Z - info: [PARSER] Finished parsing 1208222291
2015-02-09T19:50:42.208Z - error: [PARSER] Error: Error: Command failed: 
2015-02-09T19:50:42.209Z - info: [PARSER] match 1220370501
2015-02-09T19:50:42.210Z - info: [PARSER] found local replay for match 1220370501
2015-02-09T19:50:42.210Z - info: [PARSER] running parse on C:\Program Files (x86)\Steam\SteamApps\common\dota 2 beta\dota\replays\1220370501.dem
2015-02-09T19:50:42.709Z - info: [PARSER] Finished parsing 1220370501
2015-02-09T19:50:42.709Z - error: [PARSER] Error: Error: Command failed: 
2015-02-09T19:50:42.710Z - info: [PARSER] match 1208178491
2015-02-09T19:50:42.710Z - info: [PARSER] found local replay for match 1208178491
2015-02-09T19:50:42.710Z - info: [PARSER] running parse on C:\Program Files (x86)\Steam\SteamApps\common\dota 2 beta\dota\replays\1208178491.dem
2015-02-09T19:50:43.116Z - info: [PARSER] Finished parsing 1208178491
2015-02-09T19:50:43.117Z - error: [PARSER] Error: Error: Command failed: 
2015-02-09T19:50:43.117Z - info: [PARSER] match 1208107912
2015-02-09T19:50:44.416Z - info: [STEAM] Logged on.
2015-02-09T19:50:44.421Z - info: [STEAM] Received servers.


![error d2rpm](https://cloud.githubusercontent.com/assets/10925324/6114326/561f013c-b06b-11e4-93ce-7135010186ff.png)

**Comment by pyarmak** [comment] 2015-02-09 19:58
Very interesting. So there's no actual crash occurring. 
Could you post a screenshot of your settings or simply tell we what settings you have set?
Do the browser tabs open automatically?
Do you have Java installed on your system?
Do you have this file present on your system: ```<D2RM install path>\D2RM\node-webkit\parser\dist\parser.exe```?

Right now I suspect that for some reason the linux specific code is firing on your system. I'm just trying to get a more complete picture though.

**Comment by ltfuzzle** [comment] 2015-02-09 21:20
The browser tabs open automaticly. I have java installed and updated on my system. I will go over my settings later when I get back to my desktop.

**Comment by ltfuzzle** [comment] 2015-02-11 15:01
As far as the settings tab, I have all of these checked ON:
Track Steam Account
Scrape Full History
Parse All Replays
Every other setting is unchecked.

I also have the parser.exe in the location you listed above.

**Comment by icheyne** [comment] 2015-02-11 21:49
I'm getting this too.

To reproduce:
# Open d2rm
# Sync

Firefox opens with ~9 tabs all telling me to update to the latest version of Java, even though I'm on version 8 update 31.

I can also reproduce it by trying to download a replay.

http://cheyne.net/tmp/exceptions.log
http://cheyne.net/tmp/dota.log

**Comment by pyarmak** [comment] 2015-02-11 22:07
Ok can one of you try running the parser file manually for me?
Go to ```<D2RM install path>\D2RM\node-webkit\parser\dist``` then open a command prompt in this directory (shift + right mouse click inside folder -> Open command window here) then run the following command:
```parser.exe "<path to a replay file>"```

**Comment by icheyne** [comment] 2015-02-11 23:40
I ran it exactly as you instructed and a Firefox "Download Free Java Software" tab opened.

**Comment by pyarmak** [comment] 2015-02-12 00:09
I must've done something wrong when I wrapped the JRE and jar into an executable. Good catch.
I will take a look and build a new one and put it here for you guys to test.

**Comment by pyarmak** [comment] 2015-02-12 03:22
Ok so I've decided that I'm going to change the way I distribute the parser on windows. 
I will no longer wrap it into an exe file but instead during the installation of the app check that the minimum required version of java (1.7) is installed and prompt the used to download it if it's not. This way I won't be forcing people to download an extra ~130mb during every update of the app.

That being said, I won't be releasing anything new until version 0.3.0 so in the meantime, you guys can try [this](https://www.dropbox.com/s/vlq5aa9mndjmirr/parser.exe?dl=0) exe out (just replace the old one).

**Comment by icheyne** [comment] 2015-02-12 23:12
That works great! Thank you.

One small comment now that the app finally works for me, is that it's not obvious when you load up a match that you can download it to get much more interesting data. A first time user of d2rm might miss this powerful functionality and decide that Dotabuff does everything they need.

**Comment by pyarmak** [comment] 2015-02-13 09:35
That's a good point.
A number of people have actually asked me "well why should I use this over dotabuff" and while I could go on a long rant about why they should, I would much prefer to be able to point them to something instead.
I will also need to get a nice setup guide going at some point and maybe make a video overview of all the features (though I'm not very good at making videos and my microphone is pretty crappy).

**Comment by icheyne** [comment] 2015-02-13 10:34
Hmm. Few people will bother with video or text guides. The effort would be better spent working on a setup wizard or some king of in-app tutorial or simply some tooltips to point out the functionality.

**Comment by pyarmak** [comment] 2015-02-14 22:39
hmm well I've already made like every setting have a tooltip in the settings panel.
I think the trailer would be the best idea but I don't have any video editing skills haha

By the way, the next release should be coming fairly soon. I'm going to be bold and say on Monday.
Some nice usability improvements such as a status bar for replay downloads and some more nifty features.
Here's a sneak peak:
![hero_pie_graph](https://cloud.githubusercontent.com/assets/1577549/6201324/4be61c4c-b470-11e4-82c3-81030d3f4bfa.gif)

**Comment by icheyne** [comment] 2015-02-15 00:30
Nice!

**Comment by pyarmak** [comment] 2015-02-17 22:24
I am closing this with the release of v0.3.0.

**Closed by pyarmak** 2015-02-17 22:24 UTC
